In [2]:
import pandas as pd

In [3]:
all_deaths = pd.read_csv("./classified_all_deaths_07282026_regex.csv")

/tmp/ipykernel_735256/3305256161.py:1: DtypeWarning: Columns (0,30,32,33,35,36,40) have mixed types. Specify dtype option on import or set low_memory=False.
  all_deaths = pd.read_csv("./classified_all_deaths_07282026_regex.csv")

In [4]:
all_ods = pd.read_csv("./pipeline_steps/input_files/2012-01-2026-04-overdoses.csv")

/tmp/ipykernel_735256/2537799894.py:1: DtypeWarning: Columns (27,29,38,48) have mixed types. Specify dtype option on import or set low_memory=False.
  all_ods = pd.read_csv("./pipeline_steps/input_files/2012-01-2026-04-overdoses.csv")

In [5]:
all_ods_deaths = all_deaths[all_deaths['Any Drugs'] == 1]

In [6]:
all_ods_deaths

,Age,Gender,Race,DeathDate,DeathPlace,DeathCity,EventPlace,EventCity,Mode,CauseA,...,EventZip,SourcePages,CaseNumber,MiddleName,DeathTime,ResidenceType,ExperiencingHomelessness,HowInjuryOccurred,DateofBirth,Text
14,51.0,MALE,ASIAN,2012-01-01,DRIVEWAY,LAKEWOOD,DRIVEWAY,LAKEWOOD,ACCIDENT,EFFECTS OF METHAMPHETAMINE INTAKE,...,90715.0,NaN,2012-00017,MONTANO,16:48:00,NaN,NaN,DRUG INTAKE,1960-11-25,"EFFECTS OF METHAMPHETAMINE INTAKE, DRUG INTAKE"
16,56.0,MALE,LATINE,2012-01-01,SIDEWALK,WILMINGTON,UNKNOWN,NaN,ACCIDENT,ETHANOL INTOXICATION,...,NaN,NaN,2012-00007,NaN,07:18:00,NaN,NaN,ALCOHOL INGESTION,1955-09-20,"ETHANOL INTOXICATION, CORONARY ATHEROSCLEROSIS..."
18,50.0,MALE,LATINE,2012-01-01,HOSPITAL,MONTEBELLO,UNKNOWN,NaN,ACCIDENT,Combined effects of heroin-morphine and ethanol,...,NaN,NaN,2012-00018,WAYNE,18:48:00,NaN,NaN,DRUG INTAKE,1961-07-22,Combined effects of heroin-morphine and ethano...
27,49.0,MALE,LATINE,2012-01-02,HOSPITAL,PALMDALE,~ NO TRAUMA ~,NaN,NATURAL,GASTROINTESTINAL HEMORRHAGE,...,NaN,NaN,2012-00023,ALLEN,07:10:00,NaN,NaN,NaN,1962-02-27,"GASTROINTESTINAL HEMORRHAGE, RUPTURE ESOPHAGEA..."
29,36.0,MALE,WHITE,2012-01-02,HOSPITAL,PASADENA,NaN,NaN,NATURAL,UPPER GASTROINTESTINAL HEMORRHAGE,...,NaN,NaN,2012-00054,ALLEN,16:15:00,INDIGENT - HOMELESS,NaN,NaN,1975-04-08,"UPPER GASTROINTESTINAL HEMORRHAGE, ESOPHAGEAL ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146003,55 years,MALE,BLACK,2026-04-05,Residence,Los Angeles,NaN,NaN,NATURAL,CHRONIC ALCOHOL USE,...,NaN,"37248,37249,37250,37251,37252,37253,37254,3725...",2026-05640,NaN,NaN,Residence,NaN,NaN,NaN,CHRONIC ALCOHOL USE
146011,23 years,MALE,BLACK,2026-04-05,Residence,Los Angeles,Residence,Los Angeles,SUICIDE,ASPHYXIA,...,90034,"37248,37249,37250,37251,37252,37253,37254,3725...",2026-05612,NaN,NaN,Residence,NaN,INTENTIONALLY PLACED A PLASTIC BAG OVER HIS HE...,NaN,"ASPHYXIA, PLASTIC BAG SUFFOCATION WITH INERT G..."
146017,52 years,FEMALE,WHITE,2026-04-06,Hospital,Los Angeles,NaN,NaN,ACCIDENT,END STAGE RENAL DISEASE,...,NaN,"37248,37249,37250,37251,37252,37253,37254,3725...",2026-05738,NaN,NaN,NaN,NaN,DRUG INTAKE,NaN,"END STAGE RENAL DISEASE, TYPE 2 DIABETES, COCA..."
146032,47 years,FEMALE,BLACK,2026-04-08,Hospital,Inglewood,NaN,NaN,NATURAL,"SEQUELAE OF LIVER FAILURE, CLINICAL",...,NaN,"37260,37261,37262,37263,37264,37265,37266,3726...",2026-05848,NaN,NaN,Residence,NaN,NaN,NaN,"SEQUELAE OF LIVER FAILURE, CLINICAL, PROBABLE ..."
146048,59 years,MALE,NaN,2026-04-10,Residence,NaN,NaN,NaN,NATURAL,ATHEROSCLEROTIC CARDIOVASCULAR DISEASE,...,NaN,"37260,37261,37262,37263,37264,37265,37266,3726...",2026-05969,NaN,NaN,Residence,NaN,NaN,NaN,"ATHEROSCLEROTIC CARDIOVASCULAR DISEASE, CHRONI..."

In [7]:
all_ods.columns

Index(['Age', 'Gender', 'Race', 'DeathDate', 'DeathPlace', 'DeathCity',
       'EventPlace', 'EventCity', 'Mode', 'CauseA', 'CauseB', 'CauseOther',
       'Methamphetamine', 'Heroin', 'Cocaine', 'Fentanyl', 'Alcohol',
       'Prescription.opioids', 'Any Opioids', 'Benzodiazepines', 'Others',
       'Any Drugs', 'Number_Substances', 'Polysubstance', 'source_file',
       'CaseNumber', 'DeathAddress', 'DeathZip', 'EventAddress', 'EventZip',
       'HowInjuryOccurred', 'Text', 'used_death_address', 'lon', 'lat',
       'in_la_county', 'SourcePages', 'ResidenceType', 'DeathTime',
       'ExperiencingHomelessness', 'Address', 'CT20', 'LABEL', 'ShapeSTArea',
       'ShapeSTLength', 'ZIPCODE', 'Shape_Length', 'Shape_Area',
       'DateOfBirth'],
      dtype='object')

In [8]:
in_all_ods_not_all_ods_deaths = all_ods[~all_ods['CaseNumber'].isin(all_ods_deaths['CaseNumber'])]
in_all_ods_deaths_not_all_ods = all_ods_deaths[~all_ods_deaths['CaseNumber'].isin(all_ods['CaseNumber'])]

In [11]:
in_all_ods_not_all_ods_deaths

Empty DataFrame
Columns: [Age, Gender, Race, DeathDate, DeathPlace, DeathCity, EventPlace, EventCity, Mode, CauseA, CauseB, CauseOther, Methamphetamine, Heroin, Cocaine, Fentanyl, Alcohol, Prescription.opioids, Any Opioids, Benzodiazepines, Others, Any Drugs, Number_Substances, Polysubstance, source_file, CaseNumber, DeathAddress, DeathZip, EventAddress, EventZip, HowInjuryOccurred, Text, used_death_address, lon, lat, in_la_county, SourcePages, ResidenceType, DeathTime, ExperiencingHomelessness, Address, CT20, LABEL, ShapeSTArea, ShapeSTLength, ZIPCODE, Shape_Length, Shape_Area, DateOfBirth]
Index: []

[0 rows x 49 columns]

In [12]:
in_all_ods_deaths_not_all_ods

Empty DataFrame
Columns: [Age, Gender, Race, DeathDate, DeathPlace, DeathCity, EventPlace, EventCity, Mode, CauseA, CauseB, CauseC, CauseD, CauseOther, Methamphetamine, Heroin, Cocaine, Fentanyl, Alcohol, Prescription.opioids, Any Opioids, Benzodiazepines, Others, Any Drugs, Number_Substances, Polysubstance, source_file, FirstName, LastName, DeathAddress, DeathZip, EventAddress, EventZip, SourcePages, CaseNumber, MiddleName, DeathTime, ResidenceType, ExperiencingHomelessness, HowInjuryOccurred, DateofBirth, Text]
Index: []

[0 rows x 42 columns]

In [10]:
in_all_ods_not_all_ods_deaths.Text.tolist()

[]