In [1]:
import pandas as pd

In [2]:
overdose_df = pd.read_pickle("../../data/outcomes_squashed/combined_data.pkl")

In [3]:
overdose_df[overdose_df['text'] == 'COMPLICATIONS, OF, TOXIC, ENCEPHALOPATHY, DUE, TO, TOXIC, EFFECTS, OF, TOLAZAMIDE, NONE']

,text,vector,clinBERTEmbed,GloVE_proc,Methamphetamine,Heroin,Cocaine,Fentanyl,Alcohol,Prescription.opioids,Any Opioids,Benzodiazepines,Others,Any Drugs
29663,"COMPLICATIONS, OF, TOXIC, ENCEPHALOPATHY, DUE,...","[-0.00431435684, 8.53994308e-05, -1.496199e-17...","[[0.12069881, 0.11009505, -0.30944827, 0.59526...","[0.5635970132425427, 0.8848589919507504, 2.982...",0,0,0,0,0,0,0,0,0,0

In [4]:
overdose_df[overdose_df['text'] == 'COMPLICATIONS, OF, TOXIC, ENCEPHALOPATHY, DUE, TO, TOXIC, EFFECTS, OF, TOLAZAMIDE, NONE']['Others'] = 1

/tmp/ipykernel_3850112/2634100326.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  overdose_df[overdose_df['text'] == 'COMPLICATIONS, OF, TOXIC, ENCEPHALOPATHY, DUE, TO, TOXIC, EFFECTS, OF, TOLAZAMIDE, NONE']['Others'] = 1

In [5]:
mask = overdose_df['text'] == 'COMPLICATIONS, OF, TOXIC, ENCEPHALOPATHY, DUE, TO, TOXIC, EFFECTS, OF, TOLAZAMIDE, NONE'

In [6]:
overdose_df.loc[mask, ["Others", "Any Drugs"]] = 1

In [7]:
overdose_df[overdose_df['text'] == 'COMPLICATIONS, OF, TOXIC, ENCEPHALOPATHY, DUE, TO, TOXIC, EFFECTS, OF, TOLAZAMIDE, NONE']

,text,vector,clinBERTEmbed,GloVE_proc,Methamphetamine,Heroin,Cocaine,Fentanyl,Alcohol,Prescription.opioids,Any Opioids,Benzodiazepines,Others,Any Drugs
29663,"COMPLICATIONS, OF, TOXIC, ENCEPHALOPATHY, DUE,...","[-0.00431435684, 8.53994308e-05, -1.496199e-17...","[[0.12069881, 0.11009505, -0.30944827, 0.59526...","[0.5635970132425427, 0.8848589919507504, 2.982...",0,0,0,0,0,0,0,0,1,1

In [8]:
mask = overdose_df['text'] == 'COMPLICATIONS, OF, PROBABLE, COMBINED, DRUG, TOXICITY, PROBABLE, CLONAZEPAM, AND, POSSIBLE, OPIOID, AND, ESZOPICLONE'
overdose_df.loc[mask, ["Others", "Any Drugs"]] = 1

In [9]:
overdose_df[overdose_df['text'] == 'COMPLICATIONS, OF, PROBABLE, COMBINED, DRUG, TOXICITY, PROBABLE, CLONAZEPAM, AND, POSSIBLE, OPIOID, AND, ESZOPICLONE']

,text,vector,clinBERTEmbed,GloVE_proc,Methamphetamine,Heroin,Cocaine,Fentanyl,Alcohol,Prescription.opioids,Any Opioids,Benzodiazepines,Others,Any Drugs
3818,"COMPLICATIONS, OF, PROBABLE, COMBINED, DRUG, T...","[-0.024020295020000002, 0.009857284083, -6.472...","[[0.2820914, 7.778011e-05, 0.039629687, 0.5165...","[1.1107050087302923, 1.3071235905517824, 0.960...",0,0,0,0,0,0,1,1,1,1

In [10]:
mask = overdose_df['text'] == 'ACUTE, ISOTONITAZENE, INTOXICATION'
overdose_df.loc[mask, ["Any Opioids", "Any Drugs"]] = 1

In [11]:
overdose_df[overdose_df['text'] == 'ACUTE, ISOTONITAZENE, INTOXICATION']

,text,vector,clinBERTEmbed,GloVE_proc,Methamphetamine,Heroin,Cocaine,Fentanyl,Alcohol,Prescription.opioids,Any Opioids,Benzodiazepines,Others,Any Drugs
31582,"ACUTE, ISOTONITAZENE, INTOXICATION",0,"[[0.32212365, 0.02413829, -0.006727613, 0.6150...","[0.35951003432273865, -0.292650043964386, 0.82...",0,0,0,0,0,0,1,0,0,1

In [13]:
mask = overdose_df['text'] == 'ACUTE, INTOXICATION, FROM, THE, COMBINED, EFFECTS, OF, COCAINE, FENTANYL, ZOLPIDEM, 7, AMINO, CLONAZEPAM, BUPROPION, VERAPAMIL, AND, ALCOHOL'
overdose_df.loc[mask, ["Others"]] = 1

In [19]:
mask = overdose_df['text'] == 'ACUTE, FENTANYL, FLUAPRAZOLAM, AND, COCAINE, TOXICITY, INGESTION, OF, DRUGS'
overdose_df.loc[mask, ["Benzodiazepines"]] = 1

In [ ]:
overdose_df[overdose_df['text'] == 'ACUTE, FENTANYL, FLUAPRAZOLAM, AND, COCAINE, TOXICITY, INGESTION, OF, DRUGS']

In [21]:
overdose_df.to_pickle("../../data/outcomes_squashed/combined_data_removing_mislabels.pkl")